import { PR_TIMEOUT_MS, PROJECT_DIR } from "@/lib/constants";
import { execInWorkspace } from "@/lib/workspace/exec";
import type { BlueprintStep } from "../types";

/**
 * Create the PR creation step (R004).
 *
 * Runs `gh pr create` with a templated title and body. Captures the
 * PR URL from stdout and includes it in the result message for
 * downstream extraction by the worker.
 */
export function createPRStep(): BlueprintStep {
  return {
    name: "pr-create",
    async execute(ctx) {
      const start = Date.now();

      // Build title: "hive: <truncated prompt>"
      const titlePrompt = ctx.prompt.length > 60 ? `${ctx.prompt.slice(0, 57)}...` : ctx.prompt;
      const title = `hive: ${titlePrompt}`;

      // Build body with task context
      const body = [
        "## Task",
        "",
        ctx.prompt,
        "",
        "---",
        "",
        `*Task ID: ${ctx.taskId}*`,
        "",
        "*This PR was automatically generated by Hive.*",
      ].join("\n");

      // Escape for shell: single quotes in title/body would break the command.
      // Use base64 to avoid all shell injection issues.
      const titleB64 = Buffer.from(title, "utf-8").toString("base64");
      const bodyB64 = Buffer.from(body, "utf-8").toString("base64");

      // Quote branch name defensively to prevent shell injection
      const safeBranch = ctx.branchName.replace(/'/g, "'\"'\"'");

      const cmd = [
        `cd ${PROJECT_DIR}`,
        `&& gh pr create`,
        `--title "$(echo '${titleB64}' | base64 -d)"`,
        `--body "$(echo '${bodyB64}' | base64 -d)"`,
        `--base main`,
        `--head '${safeBranch}'`,
      ].join(" ");

      const result = await execInWorkspace(ctx.workspaceName, cmd, {
        timeoutMs: PR_TIMEOUT_MS,
      });

      if (result.exitCode !== 0) {
        const stderr = result.stderr.slice(0, 500);
        const msg = `gh pr create failed: ${stderr}`;
        console.log(`[blueprint] pr-create: ${msg} (task=${ctx.taskId})`);
        return { status: "failure", message: msg, durationMs: Date.now() - start };
      }

      // gh pr create outputs the PR URL on success
      const prUrl = result.stdout.trim();

      // Validate URL before treating as success
      try {
        new URL(prUrl);
      } catch {
        const msg = `gh pr create produced invalid URL: ${prUrl}`;
        console.log(`[blueprint] pr-create: ${msg} (task=${ctx.taskId})`);
        return { status: "failure", message: msg, durationMs: Date.now() - start };
      }

      // Persist PR URL onto context so the worker can store it on the Task record
      ctx.prUrl = prUrl;

      const msg = `PR created: ${prUrl}`;
      console.log(`[blueprint] pr-create: ${msg} (task=${ctx.taskId})`);
      return { status: "success", message: msg, durationMs: Date.now() - start };
    },
  };
}
