import { execFile } from "child_process";
import { DEFAULT_EXEC_TIMEOUT_MS } from "@/lib/constants";

export interface ExecOptions {
  timeoutMs?: number;
  loginShell?: boolean;
}

export interface ExecResult {
  stdout: string;
  stderr: string;
  exitCode: number;
}

/**
 * Convert a Coder workspace name (e.g. "ai-dev-01.main") to an SSH host
 * that matches the config generated by `coder config-ssh`.
 */
function toSshHost(workspaceName: string): string {
  return `coder.${workspaceName}`;
}

/**
 * Execute a command inside a Coder workspace via native SSH with PTY disabled.
 * Uses `coder config-ssh` generated SSH config for routing.
 * By default runs the command directly. Set `loginShell: true` to wrap
 * in `bash -l -c` for commands that need nvm/pnpm on PATH.
 * Never throws on non-zero exit — always returns a structured ExecResult.
 */
export function execInWorkspace(
  workspaceName: string,
  command: string,
  opts?: ExecOptions,
): Promise<ExecResult> {
  const timeoutMs = opts?.timeoutMs ?? DEFAULT_EXEC_TIMEOUT_MS;
  const loginShell = opts?.loginShell ?? false;
  const truncatedCmd =
    command.length > 100 ? command.slice(0, 100) + "…" : command;

  console.log(
    `[exec] workspace=${workspaceName} cmd="${truncatedCmd}" timeout=${timeoutMs}ms`,
  );

  const sshHost = toSshHost(workspaceName);
  const shellCmd = loginShell
    ? `bash -l -c ${shellQuote(command)}`
    : command;

  const args = ["-T", "-o", "BatchMode=yes", sshHost, shellCmd];

  return new Promise((resolve) => {
    execFile(
      "ssh",
      args,
      { timeout: timeoutMs },
      (error, stdout, stderr) => {
        if (error) {
          if (
            error.killed ||
            (error as NodeJS.ErrnoException).code ===
              "ERR_CHILD_PROCESS_TIMEOUT"
          ) {
            console.log(
              `[exec] workspace=${workspaceName} cmd="${truncatedCmd}" timed out after ${timeoutMs}ms`,
            );
            resolve({
              stdout: stdout ?? "",
              stderr:
                stderr || `Command timed out after ${timeoutMs}ms`,
              exitCode: 124,
            });
            return;
          }

          const exitCode =
            typeof (error as NodeJS.ErrnoException).code === "number"
              ? ((error as NodeJS.ErrnoException).code as unknown as number)
              : 1;
          console.log(
            `[exec] workspace=${workspaceName} cmd="${truncatedCmd}" exitCode=${exitCode}`,
          );
          resolve({
            stdout: stdout ?? "",
            stderr: stderr ?? error.message,
            exitCode,
          });
          return;
        }

        console.log(
          `[exec] workspace=${workspaceName} cmd="${truncatedCmd}" exitCode=0`,
        );
        resolve({ stdout: stdout ?? "", stderr: stderr ?? "", exitCode: 0 });
      },
    );
  });
}

function shellQuote(s: string): string {
  return `'${s.replace(/'/g, "'\\''")}'`;
}
